package bot.userData.rpg.questData;

public enum QuestStep {
	ANSWERING_QUESTIONS, //
	BERSERKER_1, //
	BERSERKER_2, //
	BERSERKER_3, //
	BERSERKER_4, //
	CHOOSE_CLASS, //
	CHOPPING_WOOD, //
	CLEARING_MINE, //
	COLLECTING_SWORDS, //
	FINISHED, //
	FLUFFING, //
	GATHERING_RESOURCES, //
	GETTING_ARACHNE_SILK, //
	GETTING_BAROMETZ_COTTON, //
	GETTING_PRISONER_FRUIT, //
	GETTING_SLIME_JELLY, //
	GETTING_TOOLS, //
	GETTING_WERESHEEP_WOOL, //
	MAGE_1, //
	MAGE_2, //
	MAGE_3, //
	MAGE_4, //
	PALADIN_1, //
	PALADIN_2, //
	PALADIN_3, //
	RANGER_1, //
	RANGER_2, //
	RANGER_3, //
	ROGUE_1, //
	ROGUE_2, //
	ROGUE_3, //
	SEARCHING_FOR_ACORNS, //
	SEARCHING_FOR_TEDDY, //
	SEARCHING_FOR_THE_BOOK, //
	STEP_0, //
	STEP_1, //
	STEP_2, //
	STEP_3, //
	STEP_4, //
	TALKING_TO_RIVAL, //
	WAITING, //
	WARLOCK_1, //
	WARLOCK_2, //
	WARLOCK_3, //
	WARLOCK_4,//
	;
}